# Generated by Django 5.0 on 2023-12-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=100)),
                ('e_post', models.CharField(max_length=100)),
                ('e_contact', models.CharField(max_length=15)),
                ('e_email', models.EmailField(max_length=254)),
                ('e_salary', models.IntegerField()),
                ('e_address', models.CharField(max_length=500)),
                ('e_city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
